### ISSUE TITLE
Re-add Actions menu shortcut/add shortcut for archiving

### ISSUE THREAD

**Issue by tvqt** [guoguo12/messenger-shortcuts#17]
it appears that the shortcut for the action menu has disappeared? It would be great if that feature made a comeback! It would be super super useful to me

thank you!!

**Comment by guoguo12** [comment]
Alt+Shift+A? Still works for me.  (Maybe Messenger is A/B-testing something?)

**Comment by tvqt** [comment]
that's weird- seems to work now (???)

**Comment by guoguo12** [comment]
Closing for now.
