### ISSUE TITLE
Help information not formatted correctly (Chrome on ChromeOS/Debian)

### ISSUE THREAD

**Issue by nitsanshai** [guoguo12/messenger-shortcuts#20]
![vh9lwxqerqr](https://user-images.githubusercontent.com/4978492/42767779-bfd6c0cc-88d2-11e8-9bdf-f7182fea7e42.png)

**Comment by guoguo12** [comment]
Wow, that's ugly. Thanks for reporting!

**Comment by nitsanshai** [comment]
Actually, just tried it on linux (debian) chrome, looks the same as above.

**Comment by guoguo12** [comment]
Is there anything about your setup that is unique or uncommon?

**Comment by heidid** [comment]
I'm having the same issue on Chrome (v71.0.3578.98) with Windows 10.

**Comment by guoguo12** [comment]
Thanks! I can reproduce this. Will fix.

**Comment by guoguo12** [comment]
Alright, I think I fixed it in 2.2.3 (publishing in progress).

If it's still broken in 2.2.3, feel free to reopen this issue.
