### ISSUE TITLE
chromebook conflict

### ISSUE THREAD

**Issue by cauerego** [guoguo12/messenger-shortcuts#21]
here we have ALT+1 up to ALT+9 to switch apps from the taskbar.

this conflicts heavily with facebook shortcuts to go to different pages, such as home or messenger...

and messes up completely the messenger "web app" which we can create.

do you think the extension could fix this? i wouldn't care to simply remove these conflicting fb's shortcuts.

**Comment by guoguo12** [comment]
So you're saying the `Alt+Shift+n` shortcut is broken on Chrome OS?

**Comment by cauerego** [comment]
no Idea about shift. and it's a bug on Chromebook from Facebook, not on your extension.

i was hoping the extension could help, by offering someway to customize fb default shortcuts. because they're broken in that way.

**Comment by guoguo12** [comment]
Oh, I see. Thanks for the request, but that sounds like it's beyond the scope of the extension.

**Comment by cauerego** [comment]
cool. thanks for the reply. worth the shot. 😉
