### ISSUE TITLE
Publish Firefox WebExtension

### ISSUE THREAD

**Issue by sarangjo** [guoguo12/messenger-shortcuts#4]
As it turns out, all of the exact same source code is sufficient to create a Firefox WebExtension! I think it would be nice to have this extended to both browsers, since it shouldn't take too long to [publish](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Publishing_your_WebExtension)!

**Comment by guoguo12** [comment]
Thanks, I didn't know that! I don't have time to publish/test it this week, so if you want to make an official fork of this extension for Firefox, you have my blessing. (Otherwise, I'll look into it next week.)

**Comment by sarangjo** [comment]
Sounds good, I'll go ahead and make the fork!

**Comment by guoguo12** [comment]
Cool, thanks! Let me know if there's anything I can help with.

**Comment by sarangjo** [comment]
Congrats, the add-on is in the review stage! :)
